### Teste de Criação de Curso
POST http://localhost:3005/cursos HTTP/1.1
Content-Type: application/json

{
  "nome": "Curso de Desenvolvimento Web",
  "descricao": "Curso completo de desenvolvimento web com front-end e back-end.",
  "cargaHoraria": "200 horas",
  "gradeCurricular": "Front-end, Back-end, Banco de Dados, Node.js, React.",
  "dataInicio": "2024-01-01T00:00:00Z",
  "dataFim": "2024-01-01T00:00:00Z",
  "professor": 5
}

###

### Obter Todos os Cursos
GET http://localhost:3005/cursos HTTP/1.1
Content-Type: application/json

###

### Obter um Curso por ID
GET http://localhost:3005/cursos/1 HTTP/1.1
Content-Type: application/json

###

### Atualizar um Curso
PATCH http://localhost:3005/cursos/1 HTTP/1.1
Content-Type: application/json

{
  "nome": "Curso de Desenvolvimento Full Stack",
  "descricao": "Curso completo de desenvolvimento web com ênfase em Full Stack.",
  "cargaHoraria": "250 horas",
  "gradeCurricular": "Front-end, Back-end, Banco de Dados, Node.js, React, Angular.",
  "dataInicio": "2024-02-01",
  "dataFim": "2025-01-31",
  "professor": "Prof. João Silva"
}

###

### Deletar um Curso
DELETE http://localhost:3005/cursos/1 HTTP/1.1
Content-Type: application/json

###
