@env .env

### Criar um usuário
POST http://localhost:4000/api/users
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@example.com",
  "password": "123456",
  "phone": "123456789",
  "role": "STUDENT",
  "profilePicture": "http://example.com/profile.jpg"
}

### Listar todos os usuários
GET http://localhost:4000/api/users

### Obter um usuário por ID
GET http://localhost:4000/api/users/1

### Atualizar um usuário
PUT http://localhost:4000/api/users/1
Content-Type: application/json

{
  "firstName": "Jane",
  "lastName": "Doe",
  "phone": "987654321"
}

### Excluir um usuário
DELETE http://localhost:4000/api/users/1
