### Teste de Criação de Aluno
POST http://localhost:3005/alunos HTTP/1.1
Content-Type: application/json

{
  "nomeCompleto": "João da Silva",
  "email": "joewfe.silva@email.com",
  "senha": "senhaSegura123",
  "matricula": "2024145345423ewe45",
  "telefone": "11987654321",
  "escolaridade": "Superior Completo",
  "rg": "fef",
  "cpf": "123.fef.789-00",
  "LinkcomprovanteEndereco": "http://example.com/comprovante-endereco.jpg",
  "LinklaudoMedico": "http://example.com/laudo-medico.pdf",
  "LinkBne": "http://example.com/bne.pdf"
}

### Obter Todos os Alunos
GET http://localhost:3005/alunos HTTP/1.1
Content-Type: application/json


### Obter um Aluno por ID
GET http://localhost:3005/alunos/1 HTTP/1.1
Content-Type: application/json

### Atualizar um Aluno
PATCH  http://localhost:3005/alunos/1 HTTP/1.1
Content-Type: application/json

{
  "nomeCompleto": "João da Silva Oliveira",
  "email": "joao.silcsdcva.oliveira@email.com",
  "senha": "cdcscdcsc",
  "matricula": "202412cdscs345",
  "telefone": "1198765cscdc4321",
  "escolaridade": "Mestrado",
  "rg": "sdc",
  "cpf": "123.45csdc6.78dsdcsd9-00",
  "LinkcomprovanteEndereco": "http://example.com/novo-comprovante-endereco.jpg",
  "LinklaudoMedico": "http://example.com/novo-laudo-medico.pdf",
  "LinkBne": "http://example.com/novo-bne.pdf"
}

### Deletar um Aluno
DELETE http://localhost:3005/alunos/6 HTTP/1.1
Content-Type: application/json
