### Criação de um Novo Professor
POST http://localhost:3005/professores HTTP/1.1
Content-Type: application/json

{
  "nomeCompleto": "Carlos Silva",
  "email": "carlos.silva@email.com",
  "senha": "senhaSegura123",
  "telefone": "11987654321",
  "rg": "123456789",
  "cpf": "123.456.789-00",
  "endereco": "Rua das Flores, 123, São Paulo",
  "disciplina": "Matemática"
}

### Obter Todos os Professores
GET http://localhost:3005/professores HTTP/1.1
Content-Type: application/json

### Obter Professor por ID
GET http://localhost:3005/professores/3 HTTP/1.1
Content-Type: application/json

### Atualizar Dados de um Professor
PATCH http://localhost:3005/professores/3 HTTP/1.1
Content-Type: application/json

{
  "nomeCompleto": "Carlos Silva Pereira",
  "email": "carlos.silva.pereira@email.com",
  "senha": "novaSenhaSegura123",
  "telefone": "11987654321",
  "rg": "987654321",
  "cpf": "123.456.789-01",
  "endereco": "Avenida Paulista, 987, São Paulo",
  "disciplina": "Física"
}

### Deletar Professor
DELETE http://localhost:3005/professores/4 HTTP/1.1
Content-Type: application/json
